### ISSUE TITLE
Headless Ethernet Setup

### ISSUE THREAD

**Issue by gittusmaximus** [wrzlbrmft/arch-xu4#2]
Kia ora wrzlbrmft

Thanks heaps for this script (would've been impossible for me to run arch otherwise) however I was wondering if you could help clarify how to edit the .conf for headless setup with only Ethernet connection. 

Do I need to create ETHERNET_ESSID etc underneath the regular Ethernet settings if I wish to headlessly SSH into it or do I put my essid and key in the WIRELESS settings even though I'm after ETHERNET. 

Sorry for the poorly worded question and thanks for your time

**Comment by wrzlbrmft** [comment]
Hi and thanks for the feedback! The conf file contains options for setting up ethernet as well as wireless network connectivity, each of which you can enable/disable with `SET_ETHERNET` and `SET_WIRELESS`. The relevant settings are prefixed with `ETHERNET_` resp. `WIRELESS_`. In your case, if you only want to use ethernet, simply do the following three things:
- set `SET_ETHERNET="yes"`
- configure all `ETHERNET_*` settings appropriately
- set `SET_WIRELESS="no"` and ignore all `WIRELESS_*` settings.
There is no need to mix/combine settings.
Have fun!

**Comment by gittusmaximus** [comment]
Thanks for the reply!
Classic case of PICNIC, your script worked perfectly. I just issues my end.
All been working perfectly for 2 months.

Many thanks!

**Comment by wrzlbrmft** [comment]
Happy to hear that! :smiley:
