### ISSUE TITLE
Pacman GPG signature plonter

### ISSUE THREAD

**Issue by wallace11** [wrzlbrmft/arch-xu4#4]
I'm quite sure it's not directly related to this implementation but I thought I'd document my experience here anyway. (Maybe it's also a good idea to add it to readme?)
After installing ROM I couldn't install anything from `pacman` due to GPG signature errors. I had to do the following in order to fix it:
```
pacman-key --refresh-keys
pacman-key --recv-keys KEY (from above command)
pacman-key --lsign-key KEY
pacman -S archlinux-keyring
```

Cheers.

**Comment by wrzlbrmft** [comment]
finally added notes to the readme
